version: '3'

services:
  rest-api:
    image: dfeo/rest-api
    networks:
      - net
      - nginx-net
    volumes:
      - /root/mnt/easyorder/static:/go/src/app/static

  db:
    image: "mysql:5.7"
    volumes:
      - /root/mnt/easyorder/mysql/mysql:/var/lib/mysql
      - /root/mnt/easyorder/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net

networks:
  nginx-net:
    external: true
  net:
    ipam:
      driver: default
      config:
        -
          subnet: 172.18.0.0/16
