-- MySQL Script generated by MySQL Workbench
-- Wed May 23 22:37:47 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easyorder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easyorder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyorder` DEFAULT CHARACTER SET utf8 ;
USE `easyorder` ;

-- -----------------------------------------------------
-- Table `easyorder`.`Merchant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`Merchant` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`Merchant` (
  `MerchantID` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MerchantID`),
  UNIQUE INDEX `idMerchant_UNIQUE` (`MerchantID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyorder`.`Food`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`Food` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`Food` (
  `FoodID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Price` FLOAT NOT NULL,
  `MerchantID` INT NOT NULL,
  PRIMARY KEY (`FoodID`),
  UNIQUE INDEX `idFood_UNIQUE` (`FoodID` ASC),
  INDEX `fk_Food_Merchant_idx` (`MerchantID` ASC),
  CONSTRAINT `fk_Food_Merchant`
    FOREIGN KEY (`MerchantID`)
    REFERENCES `easyorder`.`Merchant` (`MerchantID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyorder`.`Seat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`Seat` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`Seat` (
  `SeatID` INT NOT NULL AUTO_INCREMENT,
  `Number` VARCHAR(45) NOT NULL,
  `QRCodeUrl` VARCHAR(45) NOT NULL,
  `MerchantID` INT NOT NULL,
  PRIMARY KEY (`SeatID`),
  UNIQUE INDEX `idSeat_UNIQUE` (`SeatID` ASC),
  INDEX `fk_Seat_Merchant1_idx` (`MerchantID` ASC),
  CONSTRAINT `fk_Seat_Merchant1`
    FOREIGN KEY (`MerchantID`)
    REFERENCES `easyorder`.`Merchant` (`MerchantID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyorder`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`Customer` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`Customer` (
  `CustomerID` INT NOT NULL AUTO_INCREMENT,
  `WechatID` VARCHAR(45) NOT NULL,
  `Balance` FLOAT NOT NULL DEFAULT 100.0,
  PRIMARY KEY (`CustomerID`),
  UNIQUE INDEX `idCustomer_UNIQUE` (`CustomerID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyorder`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`Order` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`Order` (
  `OrderID` INT NOT NULL AUTO_INCREMENT,
  `Status` INT NOT NULL,
  `SeatID` INT NULL,
  `CustomerID` INT NOT NULL,
  `MerchantID` INT NOT NULL,
  `OrderTime` DATETIME NOT NULL,
  `CompleteTime` DATETIME NOT NULL,
  PRIMARY KEY (`OrderID`),
  UNIQUE INDEX `idOrder_UNIQUE` (`OrderID` ASC),
  INDEX `fk_Order_Seat1_idx` (`SeatID` ASC),
  INDEX `fk_Order_Customer1_idx` (`CustomerID` ASC),
  INDEX `fk_Order_Merchant1_idx` (`MerchantID` ASC),
  CONSTRAINT `fk_Order_Seat1`
    FOREIGN KEY (`SeatID`)
    REFERENCES `easyorder`.`Seat` (`SeatID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `easyorder`.`Customer` (`CustomerID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_Merchant1`
    FOREIGN KEY (`MerchantID`)
    REFERENCES `easyorder`.`Merchant` (`MerchantID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `easyorder`.`OrderHasFood`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyorder`.`OrderHasFood` ;

CREATE TABLE IF NOT EXISTS `easyorder`.`OrderHasFood` (
  `OrderID` INT NOT NULL,
  `FoodID` INT NULL,
  `Amount` INT NULL,
  INDEX `fk_Order_has_Food_Food1_idx` (`FoodID` ASC),
  INDEX `fk_Order_has_Food_Order1_idx` (`OrderID` ASC),
  PRIMARY KEY (`OrderID`),
  CONSTRAINT `fk_Order_has_Food_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `easyorder`.`Order` (`OrderID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Order_has_Food_Food1`
    FOREIGN KEY (`FoodID`)
    REFERENCES `easyorder`.`Food` (`FoodID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
